name: 'mono-deployer'
description: 'Single line deploy action to use within leadsforce monorepo'

inputs:
  repo:
    description: 'Repository name'
    required: true
  folder:
    description: 'Which folder to use'
    required: true
  tag:
    description: 'Package tag'
    required: true
  token:
    description: 'GitHub Personal Access Token with package write permissions'
    required: true
  user:
    description: 'GitHub User'
    required: true

runs:
  using: "composite"
  steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.user }}
        password: ${{ inputs.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: "{{defaultContext}}:${{ inputs.folder }}"
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.repo }}_${{ inputs.folder }}:${{ inputs.tag }}
        cache-from: type=registry,ref=${{ inputs.repo }}_${{ inputs.folder }}:${{ inputs.tag }}
        cache-to: type=inline
        build-args: |
          NPM_TOKEN=${{ inputs.token }}